# See https://github.com/google/dagger/blob/master/WORKSPACE

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# See https://github.com/google/bazel-common
#http_archive(
#    name = "google_bazel_common",
#    strip_prefix = "bazel-common-1c225e62390566a9e88916471948ddd56e5f111c",
#    urls = ["https://github.com/google/bazel-common/archive/1c225e62390566a9e88916471948ddd56e5f111c.zip"],
#)
COMMIT_HASH = "10d45b9c9c746eb53c4e4230e604486d3a138a1f"
http_archive(
    name = "google_bazel_common",
    strip_prefix = "bazel-common-%s" % COMMIT_HASH,
    urls = ["https://github.com/senpo/bazel-common/archive/%s.zip" % COMMIT_HASH],
)

# See https://github.com/google/bazel-common/blob/master/workspace_defs.bzl
load("@google_bazel_common//:workspace_defs.bzl", "google_common_workspace_rules")
google_common_workspace_rules()

