android_sdk_repository(
    name = "androidsdk",
    api_level = 28,
    build_tools_version = "28.0.3",
)

android_ndk_repository(
    name = "androidndk",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# https://github.com/square/bazel_maven_repository
MAVEN_REPOSITORY_RULES_VERSION = "1.0"
MAVEN_REPOSITORY_RULES_SHA = "5950eb0e4a3b8fd39832e58dd30e96258526751dabdc308cc7216f74396d8d41"
http_archive(
    name = "maven_repository_rules",
    urls = ["https://github.com/square/bazel_maven_repository/archive/%s.zip" % MAVEN_REPOSITORY_RULES_VERSION],
    type = "zip",
    strip_prefix = "bazel_maven_repository-%s" % MAVEN_REPOSITORY_RULES_VERSION,
    sha256 = MAVEN_REPOSITORY_RULES_SHA,
)
load("@maven_repository_rules//maven:maven.bzl", "maven_repository_specification")

DAGGER_PROCESSOR_SNIPPET = """
# use this target
java_library(
    name = "dagger",
    exports = [":dagger_api"],
    exported_plugins = [":dagger_plugin"]
)

# alternatively-named import of the raw dagger library.
maven_jvm_artifact(
    name = "dagger_api",
    artifact = "com.google.dagger:dagger:2.20"
)

java_plugin(
    name = "dagger_plugin",
    processor_class = "dagger.internal.codegen.ComponentProcessor",
    generates_api = True,
    deps = [":dagger_compiler"],
)
"""

# See https://github.com/senpo/bazel-common/blob/master/third_party/java/auto/BUILD
AUTO_VALUE_SNIPPET = """
package(default_visibility = ["//visibility:public"])

java_library(
    name = "value",
    exports = [
        #":value_api",
        "@maven//com/google/auto/value:auto_value_annotations",
    ],
    exported_plugins = [
        ":auto_annotation_processor",
        ":auto_oneof_processor",
        ":auto_value_processor",
    ]
)

# alternatively-named import of the raw library.
maven_jvm_artifact(
    name = "value_api",
    artifact = "com.google.auto.value:auto-value:1.6.3"
)

java_plugin(
    name = "auto_annotation_processor",
    processor_class = "com.google.auto.value.processor.AutoAnnotationProcessor",
    visibility = ["//visibility:private"],
    deps = [
        ":value_api",
        "@maven//com/google/auto:auto_common",
        "@maven//com/google/auto/service:auto_service",
        "@maven//com/google/guava:guava",
    ],
)

java_plugin(
    name = "auto_oneof_processor",
    processor_class = "com.google.auto.value.processor.AutoOneOfProcessor",
    visibility = ["//visibility:private"],
    deps = [
        ":value_api",
        "@maven//com/google/auto:auto_common",
        "@maven//com/google/auto/service:auto_service",
        "@maven//com/google/guava:guava",
    ],
)

java_plugin(
    name = "auto_value_processor",
    processor_class = "com.google.auto.value.processor.AutoValueProcessor",
    deps = [
        ":value_api",
        "@maven//com/google/auto:auto_common",
        "@maven//com/google/auto/service:auto_service",
        "@maven//com/google/guava:guava",
    ],
)
"""

ANDROID_SUPPORT_VERSION = "28.0.0"
ANDROID_ARCH_VERSION = "1.1.1"

maven_repository_specification(
    name = "maven",
    repository_urls = [
        "https://repo1.maven.org/maven2",
        "https://dl.google.com/dl/android/maven2",
    ],
    artifacts = {
        "android.arch.core:common:%s" % ANDROID_ARCH_VERSION: { "insecure": True },
        "android.arch.core:runtime:%s:aar" % ANDROID_ARCH_VERSION: { "insecure": True },
        "android.arch.lifecycle:common:%s" % ANDROID_ARCH_VERSION: { "insecure": True },
        "android.arch.lifecycle:livedata:%s:aar" % ANDROID_ARCH_VERSION: { "insecure": True },
        "android.arch.lifecycle:livedata-core:%s:aar" % ANDROID_ARCH_VERSION: { "insecure": True },
        "android.arch.lifecycle:runtime:%s:aar" % ANDROID_ARCH_VERSION: { "insecure": True },
        "android.arch.lifecycle:viewmodel:%s:aar" % ANDROID_ARCH_VERSION: { "insecure": True },

        "com.android.support:animated-vector-drawable:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:appcompat-v7:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:asynclayoutinflater:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:collections:%s" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:coordinatorlayout:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:cursoradapter:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:customview:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:documentfile:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:drawerlayout:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:interpolator:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:loader:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:localbroadcastmanager:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:print:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:slidingpanelayout:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:support-annotations:%s" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:support-compat:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:support-core-ui:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:support-core-utils:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:support-fragment:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:support-vector-drawable:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:swiperefreshlayout:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:versionedparcelable:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },
        "com.android.support:viewpager:%s:aar" % ANDROID_SUPPORT_VERSION: { "insecure": True },

        "javax.annotation:jsr250-api:1.0": { "insecure": True },
        "javax.inject:javax.inject:1": { "insecure": True },
        "com.google.code.findbugs:jsr305:3.0.2": { "insecure": True },
        "com.squareup:javapoet:1.11.1": { "insecure": True },

        "com.google.guava:guava:25.0-jre": { "insecure": True },
        "com.google.errorprone:error_prone_annotations:2.1.3": { "insecure": True },
        "com.google.j2objc:j2objc-annotations:1.1": { "insecure": True },
        "org.checkerframework:checker-compat-qual:2.0.0": { "insecure": True },
        "org.codehaus.mojo:animal-sniffer-annotations:1.14": { "insecure": True },

        "com.google.auto:auto-common:0.10": { "insecure": True },
        "com.google.auto.factory:auto-factory:1.0-beta6": { "insecure": True },
        "com.google.auto.service:auto-service:1.0-rc4": { "insecure": True },
        "com.google.auto.value:auto-value-annotations:1.6.3": { "insecure": True },
        "com.google.auto.value:auto-value:1.6.3": {
            "insecure": True,
            "build_snippet": AUTO_VALUE_SNIPPET,
        },

        "com.google.dagger:dagger:2.20": {
            "insecure": True,
            "build_snippet": DAGGER_PROCESSOR_SNIPPET,
        },
        "com.google.dagger:dagger-compiler:2.20": { "insecure": True },
        "com.google.dagger:dagger-producers:2.20": { "insecure": True },
        "com.google.dagger:dagger-spi:2.20": { "insecure": True },
        "com.google.googlejavaformat:google-java-format:1.5": { "insecure": True },
        "com.google.errorprone:javac-shaded:9-dev-r4023-3": { "insecure": True },

        "com.github.bumptech.glide:glide:4.9.0:aar": { "insecure": True },
        "com.github.bumptech.glide:gifdecoder:4.9.0:aar": { "insecure": True },
        "com.github.bumptech.glide:disklrucache:4.9.0": { "insecure": True },
        "com.github.bumptech.glide:annotations:4.9.0": { "insecure": True },
    },
    dependency_target_substitutes = {
        "com.google.auto.value": {
            "@maven//com/google/auto/value:value": "@maven//com/google/auto/value:value_api"
        },
        "com.google.dagger": {
            "@maven//com/google/dagger:dagger": "@maven//com/google/dagger:dagger_api"
        },
    }
)
